### PR TITLE
Windows version

### PR DESCRIPTION
**Pull request by unamer**

### CODE REVIEW

**Comment by rofl0r** [comment]
if you want this merged, try again in a less intrusive manner, i.e.
- do not remove files i consider necessary, like the license, or Makefile
- do not move files around in the fs,
- do not break compatibility with POSIX systems
- provide an abstraction interface for the things that differ between POSIX and windows, like pthreads/locks and socket handling

**Comment by unamer** [comment]
LOL sorry, I thought you could create a new branch and merge to the new one

**Comment by rofl0r** [comment]
the abstraction interface could look like
mysocket.h
```c
#ifdef WIN32
#include <foo.h>
#define SOCKET(X, Y) win32_socket(X, Y, 0, 0)
#else
#include <sys/socket.h>
#define SOCKET(X, Y) socket(X, Y)
#endif
```
and then use SOCKET(...) in the code.
etc. do you get the idea?

btw is there really no size_t and snprintf in visual studio ? try grepping the headers. usually it should be in stdint/stddef/stdio etc.

**Comment by unamer** [comment]
Yea, I know how to program it , I just lazy when porting to windows lol....

It actually has size_t, but it cause some error I have no idea why, so just replace them all.

Size_t should be 8 bytes in amd64, 4 bytes in intel 32.

snprintf is unsafe in vs, normally we should use snprintf_s or it will generate a warning 4996 that you can't ignore, BTW wsprintfA is an API in user32.dll, it should have better performance than general implementation in msvcrtxxx.dll

**Comment by rofl0r** [comment]
> I just lazy when porting to windows lol....

...

> It actually has size_t, but it cause some error

can you show me the error ?

> snprintf is unsafe in vs, normally we should use snprintf_s

congrats, you fell victim to microsoft propaganda. [microsoft added Annex K to the C11](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm) spec in an effort to undermind the language (which is the major reason for UNIX' success). fortunately nobody apart from them implemented it. rest assured that `snprintf` is perfectly safe, unlike they want to make you believe. it's much better to simply turn off warning 4996.
performance is of absolutely no concern here btw.

**Comment by unamer** [comment]
Here is the error log.

```
1>------ Build started: Project: socks5, Configuration: Release Win32 ------
1>  server.c
1>server.c(36): warning C4133: 'function' : incompatible types - from 'int *' to 'const char *'
1>  sockssrv.c
1>sockssrv.c(188): error C2275: 'size_t' : illegal use of this type as an expression
1>          E:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h(496) : see declaration of 'size_t'
1>sockssrv.c(188): error C2146: syntax error : missing ';' before identifier 'idx'
1>sockssrv.c(188): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(189): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(189): warning C4018: '>=' : signed/unsigned mismatch
1>sockssrv.c(190): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(191): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(192): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(192): warning C4018: '<' : signed/unsigned mismatch
1>sockssrv.c(193): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(206): error C2065: 'idx' : undeclared identifier
1>sockssrv.c(209): error C2065: 'idx' : undeclared identifier
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Oops...maybe just turn that 4996 warning off. Or use ```strtoul``` instead? Definitely it will be faster than snprintf.

**Comment by rofl0r** [comment]
the size_t error is due to the following https://stackoverflow.com/questions/9903582/error-c2275-illegal-use-of-this-type-as-an-expression check 129 pts answer. basically MSVC defaults to an archaic C dialect (again, to undermine the language behind the success of UNIX) which requires to define variables at the function header.

http://blogs.msdn.com/b/vcblog/archive/2013/06/28/c-11-14-stl-features-fixes-and-breaking-changes-in-vs-2013.aspx
eventually updating to VS 2013 might fix that. or you just mingw-gcc an almost fully C99/POSIX compatible compiler. or [pelles c](http://www.smorgasbordet.com/pellesc/).

> Or use strtoul instead? Definitely it will be faster than snprintf.

again, speed is of no concern at all. whether a function call takes 1000 cycles more or less is utterly irrelevant in a scenario where you deal with huge I/O latencies.

**Comment by unamer** [comment]
Sorry for late reply. I'm very busy last week.

funny thing is , I'm using VS2013 , It doesn't work.

But we can define a new type and mimic a size_t.

**Comment by rofl0r** [comment]
> But we can define a new type and mimic a size_t.

the issue is not lack of size_t, but that VS doesn't support C99 variable declarations in the middle of the code, only after the start of a function.

**Comment by unamer** [comment]
Yea, but how do you solve this, you can't use size_t in vs.

I didn't try other compiler like lcc or gcc in windows tho. But the reason why I use vs is it can generate most efficient executable, maximum optimization.

**Comment by rofl0r** [comment]
> Yea, but how do you solve this, you can't use size_t in vs.

why? the error C2275 you're getting is because the variable is not declared at the beginning of the function. did you even read the stuff i linked?

> vs is it can generate most efficient executable, maximum optimization

maximum optimization? lol. VS is known to generate much worse code than gcc when it comes to performance. but again, there's nothing performance critical in this code, you're cargo-culting. the only thing where VS might be better is in producing tiny executables, which is only possibly with WIN32_LEAN_AND_MEAN which in turn precludes usage of some C conventions. maybe you should really give lcc (pelles c) a shot.

**Comment by unamer** [comment]
Oops,I misunderstood what you said, my bad, I fixed this error now:

just move the declaration to the top of function:

```C
static enum authmethod check_auth_method(unsigned char *buf, size_t n, struct client*client) {
	size_t idx = 1;
blah...
```
Now it works! Thanks a lot.

Yea, i actually tried lcc once, and it generates twice bigger executable than vs lol. Maybe I should give it a shot now.

**Comment by rofl0r** [comment]
i suspect pelles C has some compiler flags like `-Os` and `-s` to generate a smaller binary, or maybe it provides a `strip` command.

**Comment by unamer** [comment]
I have quite lot of experience in generating tiny executable that works in almost all windows version without worrying about msvcrt dependency lol.

First of all , do not use c standard function at all (strncat, printf, etc.), use native api or dynamically load function instead.

Second, specify program entry manually, this will make main function arguments (argc, argv) unusable , parse the argument manually by GetCommandLine and CommandLineToArgvW. 

Third, disable /GS and /EHsc( c++ exceptions), /sdl, that means you can't use __try at all, use VEH or SEH instead.

Above three steps will make your executable doesn't rely on msvc runtime at all.

Next, turn on /Ox and decrease the alignment between PE section.

Now compile in release mode, you will get a very tiny executable. 

well, actually it is not very plausible, just for fun .

**Comment by rofl0r** [comment]
> I have quite lot of experience in generating tiny executable that works in almost all windows version without worrying about msvcrt dependency lol.

well, it seems everything you list here is msvc specific. as you can probably tell by now, i'm not really interested to uglify the program so you can produce a zomg tiny binary with your crippled compiler. crippled, because obviously it doesn't fully support C. you're of course free to do with the code in your fork whatever you wish as long as the license is respected (and it explicitly states that it shall not be removed).

anyway, if you want to add support for windows in this repo here, i'm probably willing to accept a PR as long as it follows the points i lined out earlier. and that would probably mean to make it work with mingw-gcc.

**Comment by unamer** [comment]
Yea, maybe I will do it someday in the future. mingw-gcc looks promising.

I will add your license back in my repo.

**Pull request closed without merging**
